server:
  port: 4980
spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: NON_NULL
    mapper:
      PROPAGATE_TRANSIENT_MARKER: true
    parser:
      ALLOW_BACKSLASH_ESCAPING_ANY_CHARACTER: true